exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    if: ${{ failure() }}
    steps:
      - name: Execução com sucesso
        run: echo "Execução de fluxo"